name: Build and Deploy version

on:
  workflow_dispatch:
    inputs:
      pipeline:
        type: choice
        description: 'Which pipeline to run?'
        required: true
        default: 'all'
        options:
        - all
        - qadev
        - qadev2
        - release
      artifact_version:
        type: string
        description: 'Artifact version to deploy (e.g., 1.0.1)'
        required: true
        default: 'latest'

jobs:
  # =======================================================
  # Initial Build Jobs
  # =======================================================
  build_qadev:
    name: Build QADEV
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build for QADEV
        run: echo "Building for QADEV..."

  build_qadev2:
    name: Build QADEV2
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev2'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build for QADEV2
        run: echo "Building for QADEV2..."

  build_release:
    name: Build Release
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Release Candidate
        run: echo "Building Release..."

  # =======================================================
  # Pipeline Track 1: QADEV
  # =======================================================
  deploy_qadev:
    name: Deploy QADEV
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev'
    runs-on: ubuntu-latest
    needs: build_qadev
    steps:
      - name: Deploy to QADEV
        run: |
          # Use the input version for manual runs, or the commit SHA for push events
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to QADEV..."
          # Your actual deployment script would use the $VERSION_TAG variable here

  # =======================================================
  # Pipeline Track 2: QADEV2 -> SIT2 -> Training -> Partner
  # =======================================================
  deploy_qadev2:
    name: Deploy QADEV2
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev2'
    runs-on: ubuntu-latest
    needs: build_qadev2
    steps:
      - name: Deploy to QADEV2
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to QADEV2..."

  deploy_sit2:
    name: Deploy SIT2
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev2'
    runs-on: ubuntu-latest
    needs: deploy_qadev2
    steps:
      - name: Deploy to SIT2
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to SIT2..."

  deploy_training:
    name: Deploy Training
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev2'
    runs-on: ubuntu-latest
    needs: deploy_sit2
    steps:
      - name: Deploy to Training
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to Training..."

  deploy_partner:
    name: Deploy Partner
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'qadev2'
    runs-on: ubuntu-latest
    needs: deploy_training
    steps:
      - name: Deploy to Partner
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to Partner..."

  # =======================================================
  # Pipeline Track 3: SITUAT -> PREPROD -> PROD
  # =======================================================
  deploy_situat:
    name: Deploy SITUAT
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'release'
    runs-on: ubuntu-latest
    needs: build_release
    steps:
      - name: Deploy to SITUAT
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to SITUAT..."

  deploy_preprod:
    name: Deploy PREPROD
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'release'
    runs-on: ubuntu-latest
    needs: deploy_situat
    steps:
      - name: Deploy to PREPROD
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to PREPROD..."

  deploy_prod:
    name: Deploy PROD
    if: github.event_name == 'push' || github.event.inputs.pipeline == 'all' || github.event.inputs.pipeline == 'release'
    runs-on: ubuntu-latest
    needs: deploy_preprod
    steps:
      - name: Deploy to PROD
        run: |
          VERSION_TAG=${{ github.event.inputs.artifact_version || github.sha }}
          echo "Deploying artifact version: $VERSION_TAG to PROD..."
