name: Download and Read Artifact
on:
  workflow_dispatch:
jobs:
  download_and_read:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from previous run
        uses: dawidd6/action-download-artifact@v2
        with:          
          workflow: upload.yml
          name: my-artifact
          path: downloaded_artifact/
      - name: Read file contents
        run: cat downloaded_artifact/sample-file.txt
