name: Download and Read Artifact

on:
  workflow_dispatch:

jobs:
  download_and_read:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded_artifact/

      - name: Read file contents
        run: cat downloaded_artifact/sample-file.txt
