name: Upload Build Artifact
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create artifact directory
        run: mkdir -p my_artifact_folder
      - name: Create a sample file
        run: echo "Hello, world! This is a sample artifact." > my_artifact_folder/sample-file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my_artifact_folder/
